import Query from "../QueryModel/Query";
import Where from "../QueryModel/Where";
import Option from "../QueryModel/Option";
import { InsightError } from "../controller/IInsightFacade";
import Trans from "../QueryModel/Trans";

/**
 * BEGIN AI-GENERATED CODE
 * Generated by ChatGPT (OpenAI) on 2025-02-02.
 * Purpose: Implements part of QueryParser
 * Modified by Annie
 */
export default class QueryParser {
	public static parseQuery(rawQuery: any, id: string): Query {
		if (typeof rawQuery !== "object" || rawQuery === null) {
			throw new InsightError("Query must be a valid object.");
		}

		const where = QueryParser.parseWhere(rawQuery.WHERE);
		const option = QueryParser.parseOptions(rawQuery.OPTIONS);

		// let id: string;

		if ("TRANSFORMATIONS" in rawQuery) {
			const trans = QueryParser.parseTrans(rawQuery.TRANSFORMATIONS);
			// id = QueryParser.extractDatasetId(option.column, trans);
			return new Query(where, option, trans, id);
		} else {
			// id = QueryParser.extractDatasetId(option.column);
			return new Query(where, option, null, id);
		}
	}

	private static parseWhere(whereQuery: any): Where {
		if (Object.keys(whereQuery).length === 0) {
			return new Where({});
		}

		return new Where(whereQuery);
	}

	private static parseOptions(optionQuery: any): Option {
		const columns: string[] = optionQuery.COLUMNS;

		let order: string | { dir: "UP" | "DOWN"; keys: string[] } | undefined;
		if ("ORDER" in optionQuery) {
			const orderValue = optionQuery.ORDER;

			if (typeof orderValue === "string") {
				order = orderValue;
			} else if (typeof orderValue === "object") {
				order = { dir: orderValue.dir, keys: orderValue.keys };
			} else {
				throw new InsightError("ORDER must be a string or a valid sort object.");
			}
		}

		return new Option(columns, order);
	}

	private static parseTrans(transQuery: any): Trans {
		const group: string[] = transQuery.GROUP;
		const apply: any = transQuery.APPLY;
		return new Trans(group, apply);
	}
}

/**
 * END AI-GENERATED CODE
 */
