import {
	IInsightFacade,
	InsightDataset,
	InsightDatasetKind,
	InsightError,
	InsightResult,
	ResultTooLargeError,
} from "./IInsightFacade";
import QueryParser from "../QueryValidation/QueryParser";
import ValidateQuery from "../QueryValidation/ValidateQuery";
import ApplyFilter from "../QueryProcessor/ApplyFilter";
import DatasetManager from "../../src/Dataset/DatasetManager";

/**
 * This is the main programmatic entry point for the project.
 * Method documentation is in IInsightFacade
 *
 */
export default class InsightFacade implements IInsightFacade {
	public async addDataset(id: string, content: string, kind: InsightDatasetKind): Promise<string[]> {
		let datasetManager: DatasetManager;
		try {
			datasetManager = await DatasetManager.getInstance();
			await datasetManager.reloadDataset();
		} catch (error) {
			throw new InsightError("fail to get the instance" + error);
		}

		if (!(await datasetManager.addDataset(id, content, kind))) {
			throw new InsightError("add dataset failed");
		}
		return Array.from(datasetManager.getDatasetMap().keys());
	}

	public async removeDataset(id: string): Promise<string> {
		let datasetManager: DatasetManager;
		try {
			datasetManager = await DatasetManager.getInstance();
		} catch (error) {
			throw new InsightError("fail to get the instance" + error);
		}

		if (!(await datasetManager.removeDataset(id))) {
			throw new InsightError("fail to delete the dataset");
		}
		return id;
	}

	public async performQuery(query: unknown): Promise<InsightResult[]> {
		try {
			const datasetId = ValidateQuery.validQuery(query);
			const model = QueryParser.parseQuery(query, datasetId);

			const datasetManager = await DatasetManager.getInstance();
			const dataset = datasetManager.getDatasetMap().get(model.id);

			if (!dataset) {
				throw new InsightError("Dataset not found");
			}

			let whereRes = ApplyFilter.applyWhere(dataset, model.where);

			if (model.transformations) {
				whereRes = ApplyFilter.applyTrans(whereRes, model.transformations);
			}
			const optionRes = ApplyFilter.applyOptions(whereRes, model.option);

			const largestSize = 5000;
			if (optionRes.length > largestSize) {
				throw new ResultTooLargeError("Query result exceeds limit");
			}

			return optionRes;
		} catch (error) {
			throw error;
		}
	}

	public async listDatasets(): Promise<InsightDataset[]> {
		const datasetManager = await DatasetManager.getInstance();
		await datasetManager.reloadDataset();
		const datasetMap: Map<string, any[]> = datasetManager.getDatasetMap();
		const kindMap: Map<string, InsightDatasetKind> = datasetManager.getKindMap();
		const insightDatasets: InsightDataset[] = [];
		//=> Generated by Copilot
		for (const [id, datasetContent] of datasetMap.entries()) {
			const insightDataset: InsightDataset = {
				id: id,
				kind: kindMap.get(id) as InsightDatasetKind,
				numRows: datasetContent.length,
			};
			insightDatasets.push(insightDataset);
		}
		return insightDatasets;
		//<= Generated by Copilot
	}
}

// export interface InsightDataset {
// 	id: string;
// 	kind: InsightDatasetKind;
// 	numRows: number;
// }
